#!/bin/bash

PACKAGE_NAME=psij-testing-service
GIT_BASE=https://github.com/ExaWorks/$PACKAGE_NAME/archive/refs/tags
VERSION=`cat ../../RELEASE`

# The service version to build the docker container with or use for
# deployment
SERVICE_VERSION=$VERSION

# Docker image to use
IMAGE=hategan/$PACKAGE_NAME

# If DEV is not 0, the deployment script will install the service from
# the parent directory
DEV=0

# The location of the mongodb databases and customization directories
DATA_DIR=/var/lib/psi-j-testing-service

if [ "$DEV" == "1" ]; then
    DATA_DIR="$PWD/../data"
fi
